name: Magento Test Automation

on:
  push:
    branches:
      - master
      - main
      - newnhanh
  pull_request:
    branches:
      - master
      - main
      - newnhanh
  workflow_dispatch:

jobs:
  test:
    name: Run UI Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install Google Chrome (Stable)
        run: |
          sudo apt update -y
          sudo apt install -y google-chrome-stable
          google-chrome --version # Kiểm tra để đảm bảo Chrome đã được cài đặt

      - name: Install Chromedriver
        run: |
          # Cần cài đặt jq để phân tích JSON nếu chưa có
          sudo apt-get update -y
          sudo apt-get install -y jq

          # Lấy phiên bản Google Chrome đã cài đặt (chỉ major version)
          CHROME_MAJOR_VERSION=$(google-chrome --version | grep -oE 'Google Chrome ([0-9]+)\.' | cut -d' ' -f3 | tr -d '.')
          echo "Detected Chrome Major Version: $CHROME_MAJOR_VERSION"

          # Tải JSON chứa thông tin các phiên bản Chrome for Testing
          CURL_OUTPUT=$(curl -s -fL "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json")

          # Tìm URL ChromeDriver tương ứng cho phiên bản Chrome đã phát hiện
          CHROMEDRIVER_INFO=$(echo "$CURL_OUTPUT" | jq -r \
            ".versions[]? | select(.version | startswith(\"$CHROME_MAJOR_VERSION.\")) | .downloads.chromedriver[]? | select(.platform == \"linux64\") | .url")

          # Nếu không tìm thấy phiên bản cụ thể, thử tải phiên bản Stable mới nhất
          if [ -z "$CHROMEDRIVER_INFO" ] || [ "$CHROMEDRIVER_INFO" == "null" ]; then
            echo "::warning::Could not find specific ChromeDriver download URL for Chrome version $CHROME_MAJOR_VERSION. Trying latest Stable version."
            
            CHROMEDRIVER_INFO=$(echo "$CURL_OUTPUT" | jq -r \
              ".channels.Stable.downloads.chromedriver[]? | select(.platform == \"linux64\") | .url")

            if [ -z "$CHROMEDRIVER_INFO" ] || [ "$CHROMEDRIVER_INFO" == "null" ]; then
              echo "::error::Could not find any stable ChromeDriver download URL. Exiting."
              exit 1
            fi
          fi

          echo "Attempting to download ChromeDriver from: $CHROMEDRIVER_INFO"
          wget -q -O chromedriver.zip "$CHROMEDRIVER_INFO"

          # Giải nén ChromeDriver
          unzip -o chromedriver.zip

          # DI CHUYỂN CHROMEDRIVER TỪ THƯ MỤC CHÍNH XÁC
          # Tên thư mục con thường là chromedriver-linux64 hoặc chrome-linux64
          # Chúng ta sẽ di chuyển tệp thực thi nằm bên trong thư mục đó
          # Cú pháp này sẽ tìm tệp 'chromedriver' bên trong bất kỳ thư mục con nào
          find . -name "chromedriver" -exec sudo mv {} /usr/local/bin/ \;
          # Hoặc nếu bạn muốn rõ ràng hơn và biết tên thư mục là chromedriver-linux64
          # sudo mv chromedriver-linux64/chromedriver /usr/local/bin/


          sudo chmod +x /usr/local/bin/chromedriver
          echo "ChromeDriver installed to /usr/local/bin/"
          chromedriver --version # Xác nhận cài đặt thành công

      - name: Run Tests
        run: |
          dotnet test --no-build --verbosity normal
          if [ $? -ne 0 ]; then
            echo "::error::Tests failed!"
            exit 1
          fi
        env:
          HEADLESS: true