name: Magento Test Automation

on:
  push:
    branches:
      - master
      - main
      - newnhanh
  pull_request:
    branches:
      - master
      - main
      - newnhanh
  workflow_dispatch:

jobs:
  test:
    name: Run UI Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install Google Chrome and ChromeDriver
        uses: webdriverio/setup-chromedriver@v2
        with:
          chromedriver-version: 'latest'
          chrome-version: 'latest'

      - name: Run Tests
        run: |
          dotnet test --no-build --verbosity normal
          if [ $? -ne 0 ]; then
            echo "::error::Tests failed!"
            exit 1
          fi
        env:
          HEADLESS: true