name: Magento Test Automation

on:
  push:
    branches:
      - master
      - main
      - newnhanh
  pull_request:
    branches:
      - master
      - main
      - newnhanh
  workflow_dispatch:

jobs:
  test:
    name: Run UI Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # Thay thế bước cài đặt Chrome và ChromeDriver thủ công bằng action này
      - name: Install Chrome for Testing and ChromeDriver
        uses: actions/setup-chrome-and-chromedriver@v1 # Sử dụng action này
        with:
          chrome-version: 'stable' # Cài đặt phiên bản Chrome stable mới nhất
          chromedriver-version: 'stable' # Cài đặt ChromeDriver stable mới nhất

      - name: Run Tests
        run: |
          dotnet test --no-build --verbosity normal
          if [ $? -ne 0 ]; then
            echo "::error::Tests failed!"
            exit 1
          fi
        env:
          HEADLESS: true